### ISSUE TITLE
Dev to AMA upgrade path 

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#114]
Need to make it possible to switch from dev to AMA branch without it breaking existing loops.

**Comment by amazaheri** [comment]
I am waiting for our second Edison to arrive and can help with validating the upgrade process.

**Comment by bewest** [comment]
I rebased `advanced-meal-assist` onto dev over here: https://github.com/openaps/oref0/pull/119.
I tried using it, without the new features set up to see if it would issue the same results/behavior.  I had some trouble verifying if updating without "enabling" any new features would turn out the same behavior or if it should by design.  Looks like we might need to adjust how the features are turned on/off, perhaps by continuing to rely on `yargs`.
