### ISSUE TITLE
Strange sensor behavior (Libre, Dexcom G6) showing large oscillations within minutes

### ISSUE THREAD

**Issue by efbest** [openaps/oref0#1264]
I'm looking after a number of people using CGM, a decent number of patients on pumps, and a small number of loopers (I'm an endo looping since 4/2016). Recently, I noticed some strange behavior of sensors, that oscillated between extremes (see graphs). For goodness sake, most people were not realizing, what was happening. Most of them were on MDI. I have seen this only for Freestyle Libre and Dexcom G6. This is possibly due to the number of patients using these devices. I think it might be useful to apply an algorithm that identifies abrupt changes of glucose and prevents the loop from responding.
![libre1](https://user-images.githubusercontent.com/13650169/58441889-3619ba80-80e6-11e9-8459-772bd97e82e8.png)
![libre2](https://user-images.githubusercontent.com/13650169/58441890-3dd95f00-80e6-11e9-8a1a-e3c68958986d.png)
![libre3](https://user-images.githubusercontent.com/13650169/58441897-46ca3080-80e6-11e9-8b0b-812824208e91.png)

![g6-kw1](https://user-images.githubusercontent.com/13650169/58441916-7b3dec80-80e6-11e9-960c-1a2605c67d2b.png)
![g6-kw2](https://user-images.githubusercontent.com/13650169/58441936-9ad51500-80e6-11e9-9945-8b069bf98ab5.png)

**Comment by scottleibrand** [comment]
What CGM reader software are they using? All xDrip+ and/or Spike? Anyone using Dexcom’s official app?

If (as you mentioned elsewhere) none of them are using multiple sensors, then I suspect there is a bug with converting the every-minute Libre readings into uploaded readings. This is reinforced by the fact that these graphs are showing 8 readings per hour (every 7.5m) instead of 12 (every 5m), and that the oscillations diverge and reconverge regularly, usually every 6h. We should probably open another issue with the CGM reader

**Comment by scottleibrand** [comment]
Sorry, tapped “Close and comment” by accident. Still writing.

**Comment by scottleibrand** [comment]
With regard to oref0’s behavior: we the long_avgdelta, which is the delta from the average value from 15-45m ago to the most recent value, to constrain dosing. So during the worst oscillations, it would see a slight upward trend in BG, and a higher-than-actual BG, and calculate a slightly higher insulinReq as a result. With SMB disabled, it would set a high temp, and then on the next (low) oscillatory reading would set a zero temp. As a result, the total insulin delivery over a 20m+ period would be largely correct. With SMB, there is a slight asymmetry in that it could deliver half the insulinReq (rounding down), and then deliver nothing during the downtick, then issue another SMB on the next uptick. This would result in slightly higher IOB than necessary during periods of oscillation, but would self-correct as BG started to drop, and result in BG drifting low but not likely causing any serious hypo risk (absent manual overdosing). 

Based on that analysis, I believe oref0 already adequately mitigates this pattern, and we should focus our investigation on finding and fixing the root cause.

**Comment by efbest** [comment]
I'm glad oref0 takes care of the problem so far 👍😉! You are right it's necessary to get to the roots. I upload the data in my office directly (either from the machines [Libre or Dexcom G4] or their web accounts (LibreView, Dexcom Clarity). The data are imported to Diabass 5pro, a commercial software. When I look at the raw data, before importing them to Diabass, I see those 'oscillations', too!

**Comment by scottleibrand** [comment]
Dexcom receivers always report data every 5 minutes. The graphs you pasted don’t show every-5m data. If you review the original data in Dexcom Clarity, do you ever see oscillations in data showing 12 data points per hour? I’ve never seen that when uploading the data in real time to Nightscout, either via the Dexcom Share bridge or directly from the receiver or transmitter.

**Comment by keencave** [comment]
It have never seen such oscillations for the libre nor the dexcom in every discussion/chat I followed in the last 2 years. Can you provide the raw data?

**Comment by sulkaharo** [comment]
@efbest it's really critical we get to know the exact details of what CGM and reader app/hardware was used in these cases and any settings used for these apps/hardware. (As an example, just knowing xDrip was used is not actually enough to know what algorithm was used.) Also - how does Diabass 5pro get the data? Does it read it directly from a Libre or G6 hardware (as in, is this behavior exhibited in the source data produced by the algorithms and hardware stack from the manufacturer)?

**Comment by keencave** [comment]
@efbest Do you use the libre reader as data source? Does the reader deliver raw data every minute or every 15 minutes as history values? Is Diabass 5pro able the read more / other data as the Original Abbott PC software from the reader?

**Comment by tim2000s** [comment]
Is it possible that this is an issue with the data transfer to diabass? I’ve never seen data like that in either xDrip or Dexcom app (and I’ve been keeping xDrip up to date on the nightlies).

**Comment by efbest** [comment]
The solution is profane: one patient came back from a vacation (time shift 6h); the other one changed the monitor date and corrected it after a couple of days. The data have been imported to Diabass as csv-files using the export feature of LibreView and Dexcom Clarity.
