### ISSUE TITLE
Make Nightscout uploads more efficient in standard oref0-setup.sh setups

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#274]
Most oref0 users need a paid hosting solution for NS (most recommended is $7 heroku) because the latest setups are not as efficient as it could be. We need someone to take how NS uploads can be done manually, with Ben's ns-auto-crud stuff (http://openaps.readthedocs.io/en/latest/docs/walkthrough/manual/phase-1/visualization.html#set-up-ns-device) , and get that into oref0-setup.sh

**Comment by scottleibrand** [comment]
This would also allow us to stop storing Nightscout URL and API secrets information in two places: once we move everything over to the new method, we can stop adding it to crontab.  That will also make it much easier to troubleshoot when NS uploads aren't working properly.

**Comment by oschumac** [comment]
Hi Scott, what about working directly in mongo. Making a Python or Java modul Who sends data to Mongo and make sure that data is integer. So that multiply controllers are able to sync. In my xdrip wixel repo i do Uploads from python to mongo. 
Python lib pymongo is a fine solution. Is there someone with me ?

**Comment by sulkaharo** [comment]
Re: injecting directly into Mongo - @jasoncalabrese and me have actually discussed that we'd like to deprecate direct to Mongo injection altogether as a supported use case for Nightscout, as it complicates the data management a lot and is the biggest source of hosting performance issues as we need to periodically poll Mongo for changes and then diff the loaded data to in-memory data to see what to send to the client as a delta. If we only supported API access to injecting data, that'd mean the only Mongo load we need would be on the server component startup.

**Comment by oschumac** [comment]
But then we Need a method on Nighscout, that ore0 Prozess can send his recent data and Nightscout checks vor duplicates bevor injecting into mongo. Otherwise oref0 has to poll data verify and upload every 5 minutes. Thats crazy for a mobile System. We can index our local data on oref0 and send only data which are new.

**Comment by sulkaharo** [comment]
Ideally every system only sends the the changed / new events, which oref0 should already be doing. Agree Nightscout needs to de-duplicate, but this is practically impossible to guarantee with the current setup where the in-memory runtime is never guaranteed to have all data due to Mongo inserts - @jasoncalabrese let's look at doing this soon though.

**Comment by oschumac** [comment]
That is why i like the direct Access. Why should we handle everything throw ns site. When we could manage the data like i have descripted above. I know the timing on NS Site is better throw ns api. But Prozess is easier by direct Access.

**Comment by sulkaharo** [comment]
Well, if we require every client that ever injects data into Nightscout to guarantee they never insert dupes, that pretty much guarantees the system will never work. The only way to ensure no dupes exists in the data is to have the site dedupe before inserts. Always going through the API will also mean several other things, such as 1) ability to instantly push changes and notifications to every client, 2) not overload the database by frequent polling (as is happening now), 3) much simpler code and semantics for both the NS site and clients, 4) a lot more access control to the data when the master database key is never shared between apps, 5) ability to change the underlying data model without breaking clients / validate & fix broken inserts on the fly (currently every client seems to implement different field sets broken in various ways). Probably more. I understand the direct to Mongo inserts are convenient from a single developer point of view, but cause a lot of issues when you think of the overall architecture / ecosystem that is all of the Nightscout applications clients together.

**Comment by oschumac** [comment]
So what is right now the solution ? Let the NS API stay like it is, from the view of the client ?

**Comment by jasoncalabrese** [comment]
I think the ns-loop portion of the refresh loop hits NS every minute, instead of 1 time per loop, a pulls a good amount of data, reducing the number of requests is the best way to reduce load

**Comment by scottleibrand** [comment]
What would be a good check to see whether there's something new to upload without hitting NS?

**Comment by jasoncalabrese** [comment]
We could add a new property, that could be set by the openaps plugin (or maybe something more generic) and accessed similar to `/api/v2/properties/openaps?pretty=true`.  The nice thing about the properties is that they are kept in memory, so there isn't much load for extra requests.  The v1 entries/treatments apis pull from mongo, load into memory, and do a little processing, before sending to the client

**Comment by jasoncalabrese** [comment]
The properties are reloaded when new data comes in already, exposing timestamps of the last entry and treatment would let us do a quick check

**Comment by sulkaharo** [comment]
@jasoncalabrese wonder how hard it'd be to implement etag support to the api, so clients could request for data conditionally? That'd mean 1 request / minute could be very light weight if there's no new data.

**Comment by jasoncalabrese** [comment]
That might be good for entries/treatments, but there are some things like the current temp target or the timestamp of the last OpenAPS treatment that was uploaded that we could have as a property in memory

**Comment by sulkaharo** [comment]
Right, I have support for If-Modified-Since header for Entries and Treatments, which would allow cutting down data transfer hugely. Looking at my current loop code, that's not trivial change though. I'll PR the API change in soon. Maybe we could implement a ns-client app that'd support sending and reading the headers? Doing this with curl will probably be pretty painful.

**Comment by oschumac** [comment]
Yes curl is simple but for this case not the best. If a new api is there it might be usefull to create a java class which can be used in oref0 and nsClient

**Comment by ehwest** [comment]
I think a pub/sub architecture would be right for this.  Under this kind of architecture both sides keep a cursor (the publisher keeps one cursor for each subscriber) indicating what records have not yet (or have) been successfully received by the target.  There is a time-ordering  to these messages, so the cursor is really just a counter.  The cursor can be changed by the target if it wants to reset something.   This architecture extends to have multiple targets (e.g. mongodb for one, mysql for another).

BTW, I'm looking to document this whole thing and I'm strugging a bit with some facts....can someone talk to me on the phone during these holidays?

**Comment by jasoncalabrese** [comment]
We could make use of the NS websocket ap and borrow some code from the webclient and the android NSClient.  With that we'd have a small node client.

Another interesting option is to build on what I've done to run NS on the edison without mongo and add websocket sync, so 1 NS site could subscribe to another, and the NS request that we make from openaps would then point to the local NS that would take care of being in sync.

**Comment by danamlewis** [comment]
(General note that we'd like to prioritize getting this done, so will link to here if anyone reports issues with nightscout uploads from openaps rather than troubleshooting individual instances, since we know it's an ongoing issue and this is the needed solution.)

**Comment by sulkaharo** [comment]
Still working on some solutions to mitigate this. Realized I'm not sure what all the issues are that people are worried about, so if everyone could elaborate what they perceive as the problem, that'd help.

**Comment by sulkaharo** [comment]
Also to note - Ben's auto-crud implementation is a Bash script, which doesn't make supporting things like a smarter HTTP client that supports If-Modified-Since headers any easier. I have my own OpenAPS record cleaning component which tries to do things like smarter merging of Bolus Wizard events to prevent partial record uploads (food boluses with just carbs or just insulin) & mixed mmol/mg/dL data and based on implementing that, my hunch is, getting the needed logic to work using just Bash scripts will be very painful. Of course, it should be possible to refactor the system and replace the Bash bits one piece at a time.
