### ISSUE TITLE
IOB test failing right after midnight UTC

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#292]
@danamlewis committed some unrelated comments right before and after midnight UTC, and the no-op commit right after midnight UTC has a failing test: tests/iob.test.js:112:29 "IOB should calculate IOB with Temp Basals and a basal profile", with "expected 0.846 to be below 0.5"

This may indicate that our IOB calculations are somewhat incorrect right after midnight.

https://github.com/openaps/oref0/pull/291/commits/343e7b7a1e162e6ca8060e16d9716d5cdbf316d8

https://travis-ci.org/openaps/oref0/jobs/187101507

not ok 74 IOB should calculate IOB with Temp Basals and a basal profile
  AssertionError: expected 0.846 to be below 0.5
      at Assertion.fail (node_modules/should/lib/assertion.js:180:17)
      at Assertion.prop.value (node_modules/should/lib/assertion.js:65:17)
      at Context.<anonymous> (tests/iob.test.js:112:29)

**Comment by sulkaharo** [comment]
The test is broken, #293 fixes it. The issue was with the with the IOB calculation overlapping midnight with the profile set by the test not extending to cover the end of the day in a determined fashion. The next test from this specifically tests for the midnight scenario and is working as expected. What I'm wondering though is, when committing 216ec855 I tested all the tests ran at midnight, so this should have failed as well.

**Comment by sulkaharo** [comment]
Should we close this or do you want to validate the fix?
