### ISSUE TITLE
Runagain.sh should ultimately prompt for deleting cron 

### ISSUE THREAD

**Issue by danamlewis** [openaps/oref0#386]
Per @kdisimone, runagain.sh did not prompt for deleting cron after selecting y for scheduling cron (whereas it did prompt on initial run). Seems like it should.

**Comment by scottleibrand** [comment]
This was probably because you ran `~/src/oref0/bin/oref0-setup.sh` the first time, which runs the version you just updated with `git pull`, but when you ran it from oref0-runagain.sh it did `oref0-setup`, which uses the installed version.  Unless you run `npm run global-install` the installed version won't be the updated one until we do a release.

**Comment by scottleibrand** [comment]
@kdisimone you can try it again after doing `npm run global-install` in ~/src/oref0 and it should prompt you properly, or just use `~/src/oref0/bin/oref0-setup.sh` until we release the updated `oref0-setup` to master.  Please reopen if you have any issues with that.
