### ISSUE TITLE
Disappearing announced carbs & lower than expected absorption

### ISSUE THREAD

**Issue by sulkaharo** [openaps/oref0#431]
OpenAPS currently assumes announced COB absorbs and raises the BG, which causes an effect where if some carbs do not absorb due to a stomach bug or some other effect which causes lack of absorption for some time and the user also announces the rescue carbs to bring the BG up following the bolus being too much relative to the situation, the current COB algorithm will not see the carbs as absorbed, causing openaps to continue dosing relatively high amount of insulin subject to the situation where even the original bolus was too much.

Related, during a post-stomach bug low absorption period where most carbs do not absorb and where it's extremely hard to estimate the actual absorption so adjusting the ratio accurately is very hard, it looks like the best way to handle the situation is to under-report the amount of carbs / meal significantly and not announce rescue carbs. This is undocumented as a behavior and could cause autotune to get somewhat confused. (We just spent a week announcing between 15 to 20% of the consumed carbs.)

Some thoughts thereof:

1) Would it be possible to add a "reverse AMA" mode to detect if there's a sudden lack of absorption?
2) Being able to mark down rescue carbs at all times would increase the data accuracy the loop can work with, making me wonder if it'd be beneficial to have the COB algorithm be aware of bolused and unbolused carbs and deal with those separately, allowing for rescue carb marking
3) We should document the best practices for dealing with low-absorption periods like post-bug times

**Comment by scottleibrand** [comment]
One minor tweaks in dev will help with this.  To avoid over-dosing for rescue carbs, we now retroactively increase the min_5m_carbimpact to be at least half of the currentDeviation, so that if you have a spike from rescue carbs, it will reduce or eliminate the COB contribution of old unabsorbed carbs for as long as the currentDeviation is higher than 2 * min_5m_carbimpact:
https://github.com/openaps/oref0/blob/dev/lib/determine-basal/cob-autosens.js#L146-L148
Ideas for improving that kind of check would be welcome.

I wouldn't worry too much about confusing autotune by not entering rescue carbs if you still show COB when you give them.  In that case, the only effect would be that autotune doesn't adjust your CSF as much as it would have otherwise, and given that these are anomalous situations anyway, that might be be more of a feature than a bug.  :-)  The same might be true of under-entered carbs if you're doing so based on the actual expected BG rise from them.

AMA already detects when carbs aren't absorbing as expected, and only projects the current deviation to continue (not ramp up to "normal" carb absorption levels) until all carbs are absorbed (or out to DIA hours).  When carb absorption is minimal, that means a minimal effect on predictions and dosing.

I would be reluctant to bake in any assumptions about carbs entered without a bolus being rescue carbs: lots of people would prefer to be able to enter carbs well before a bolus to get AMA/SMB to handle them without a bolus.

Agreed on documenting tips and tricks for dealing with low-absorption periods, and particularly when to enter rescue carbs vs. not.

**Comment by scottleibrand** [comment]
Another mitigation that might help somewhat would be https://github.com/openaps/oref0/pull/511

**Comment by scottleibrand** [comment]
Another idea we had recently that would help with this: temporarily raise min_5m_carbimpact whenever a high temp target is running.  So if your normal target is 100, BG is trending low and you set an activity mode of 140 to compensate (or if the carbs disappear due to activity), then for the duration of the activity mode we'd use a min_5m_carbimpact of 1.4 * your normal (11.2 mg/dL/5m if you use the default of 8).

Is that worth doing?
