### ISSUE TITLE
Some closely-timed boluses go missing from nightscout uploads

### ISSUE THREAD

**Issue by mgranberry** [openaps/oref0#443]
I have noticed that some boluses "go missing" while running my pump in SMB (on a 715 if that matters).  Take this snippet of `pumphistory-zoned.json` for example:

```json
[
  {
    "_type": "Bolus", 
    "_description": "Bolus 2017-04-12T12:49:49 head[4], body[0] op[0x01]", 
    "timestamp": "2017-04-12T12:49:49-05:00", 
    "_body": "", 
    "programmed": 3.0, 
    "_head": "011e1e00", 
    "amount": 3.0, 
    "duration": 0, 
    "type": "normal", 
    "_date": "71314c0c11"
  }, 
  {
    "_type": "Bolus", 
    "_description": "Bolus 2017-04-12T12:47:53 head[4], body[0] op[0x01]", 
    "timestamp": "2017-04-12T12:47:53-05:00", 
    "_body": "", 
    "programmed": 0.2, 
    "_head": "01020200", 
    "amount": 0.2, 
    "duration": 0, 
    "type": "normal", 
    "_date": "752f4c4c11"
  }
]
```

There are two distinct boluses here, both within a couple minutes of each other.  They are not associated with a Bolus Wizard event or any other metadata, but the second and more significant bolus is being treated as ancillary to the microbolus.  I have tracked the offending code down to `oref0/lib/bolus.js`, where the state from the first bolus gets overridden by the second bolus in an attempt to combine multiple records and only a single bolus event gets generated, but I don't know enough about the Medtronic record format to know how to properly resolve this.  I am thinking that a bolus event should be generated whenever state would be overridden.  Will that cause unforeseen problems?

**Comment by scottleibrand** [comment]
Flagging this a blocking bug that needs to be fixed before releasing dev to master.

**Comment by cjo20** [comment]
What exactly is that code meant to be doing? It looks like it's finding the first bolus from any records grouped closer together than 4 minutes and ignoring the rest.

**Comment by scottleibrand** [comment]
It was intended for deduplication of boluses entered into NS and also executed on the pump.  We have since switched to a "we don't support that" stance, so if we implement stuff like https://github.com/openaps/oref0/issues/419 to clean up the remaining stragglers there, we can probably remove this deduplication check.

**Comment by scottleibrand** [comment]
For reference, the code @mgranberry is referring to is called by https://github.com/openaps/oref0/blob/dev/lib/bolus.js#L154, and calls the https://github.com/openaps/oref0/blob/dev/lib/bolus.js#L20-L29 function to do the actual comparison.  I'm not exactly sure what that `tail` variable, passed as the `remaining` argument to bolus(), actually does: this code is a little too dense for me to understand on just a read-through, so I'll probably need to do some debugging to figure it out, unless someone can annotate it a bit.

**Comment by mgranberryto** [comment]
`tail` acts as a list of recently-seen bolus record parts that get assembled into the complete bolus wizard+bolus+extended bolus record.  The problem is that when a bolus wizard record and an SMB bolus record are close together, the data gets overwritten with the oldest record and the totals may be off.  I'm afraid that Nightscout's deduplication code might also lead to missing records if they are spaced closely enough (within a minute) and have the same record type even after this is fixed.  I've been using the following patch for a while and it seems to work, with the caveat that bolus wizard records get split into separate "carb correction" and "correction bolus" records.  I suspect it would work as expected with the original `tail` variable, but I haven't tried it with the offending data.

```diff
diff --git a/lib/bolus.js b/lib/bolus.js
index ab3bca7..b49ba81 100644
--- a/lib/bolus.js
+++ b/lib/bolus.js
@@ -69,7 +69,7 @@ function reduce (treatments) {
       // console.error("remaining", remaining);
       state.eventType = '<none>';

-      state.insulin = (state.square ? state.square.amount : 0) +
+      state.insulin = (state.insulin ? state.insulin : 0) + (state.square ? state.square.amount : 0) +
                       (state.bolus ? state.bolus.amount : 0);
       var has_insulin = state.insulin && state.insulin > 0;
       var has_carbs = state.carbs && state.carbs > 0;
@@ -151,7 +151,7 @@ function reduce (treatments) {
     switch (current._type) {
       case 'Bolus':
       case 'BolusWizard':
-        var tail = within_minutes_from(current, treatments.slice(index+1), 4);
+        var tail = [] ; //  within_minutes_from(current, treatments.slice(index+1), 1);
         bolus(current, tail);
         break;
       default:
```
My current fix is ugly but it works well enough for me in practice.  The block that looks like 
```javascript
    if (ev._type == 'Bolus') {
      state.duration = ev.duration.toString( );
      // if (state.square || state.bolus) { }
      // state.insulin = (state.insulin ? state.insulin : 0) + ev.amount;
      if (ev.duration && ev.duration > 0) {
        state.square = ev;
      } else {
        state.bolus = ev;
      }
      state.created_at = state.timestamp = ev.timestamp;
      previous.push(ev);
    }
```
may need to be changed to something like this too, to make sure that at least the doses get added together.
```javascript
    if (ev._type == 'Bolus') {
      state.duration = ev.duration.toString( );
      // if (state.square || state.bolus) { }
      // state.insulin = (state.insulin ? state.insulin : 0) + ev.amount;
      if (ev.duration && ev.duration > 0) {
        state.square = ev;
      } else {
        state.bolus = (state.bolus || 0) + ev;
      }
      state.created_at = state.timestamp = ev.timestamp;
      previous.push(ev);
    }
```

**Comment by scottleibrand** [comment]
@mgranberry would your latter suggestion of adding the doses together be a workaround for bypassing Nightscout's deduplication code when there are two boluses in the same minute?

From what I can see, the 4-minute thing only applies when a BolusWizard record is involved.  Since we've seen failures to upload manual boluses that are closely timed with microboluses, I'd like to fix that particular case as well.

**Comment by scottleibrand** [comment]
I think we're stuck on this.  Does anyone have any ideas for how to modify the Nightscout deduplication behavior?

**Comment by mgranberryto** [comment]
Yes.  It appears to solve that as well.

**Comment by scottleibrand** [comment]
Can you PR "it" if you have something that you think fixes any of these problems and is ready to go?

**Comment by mgranberry** [comment]
I'll try to make some unit tests to convince myself tomorrow morning and push my hack.
