### ISSUE TITLE
Change license to be more restrictive?

### ISSUE THREAD

**Issue by seiyria** [openaps/oref0#479]
Normally, I'm not an advocate of something like this. I adore the MIT license (check out my profile and see the piles of stuff I have), but this is one case where I think there should be a more restrictive license, something like GPL3. 

MIT is great but if a medical company wants to capitalize on all of the hard work done here, they can do so freely and without consequence. The medical industry is what's causing such a problem for diabetics in the first place (I don't want to get into that here), so why make the work easier for them?

If they want to capitalize on the great work you've done, they should be required to release their derivative as well.

**Comment by scottleibrand** [comment]
We very specifically chose the MIT license for oref0 for exactly that reason: so that if a medical company wants to capitalize on all of the hard work done here, they can do so freely and without consequence.  Our objective here is to help people with diabetes, and if a company can help us do that by using some aspect of our work in their commercial products, great.  There are lot of reasons they wouldn't be willing to release any derivative work, so all a GPL3 license would do is prevent them from using what we learn to improve the products that eventually come to market.  We're not competing with the commercial medical device companies: we all have a shared goal of making things better for PWD (they just also have to make money to be able to keep doing that).

(Also, FWIW, the `openaps` toolkit is GPL licensed, as that is much less likely to be useful to anyone outside the open source world.)
