### ISSUE TITLE
Limits on extended zero temps?

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#56]
Do we need some sort of limit on how long oref0 will temp to zero, to avoid bad rebounds and potential ketones?

**Comment by sulkaharo** [comment]
Yes. The loop can currently cause a situation where the pump is enacted to zero-temp for >2 hours, if the CWD's BG doesn't raise during the time, which causes a) ketone buildup, and b) greatly increases the risk of cannula blockages. I also suspect we should implement a "minimum basal" setting, where the loop could be configured to never zero temp for more than 30 minutes within a certain time period, after which it would set the basal to a configured minimum hourly rate, to minimize cannula blockages. These also sound like an alert state would have to be implemented in these exceptional cases, where the CWD would be alerted to eat carbs instead of relying on zero temping.

**Comment by jasoncalabrese** [comment]
Maybe we could lower target after some period of low temping?  So we'd still temp to 0 if below 55 or some other limit, but would stop low temping when in the 70's, 80's, etc.

**Comment by amazaheri** [comment]
:+1:

**Comment by scottleibrand** [comment]
I think I like the simplicity of Sulka's idea: allow a configurable limit on number of minutes of zero-temp to allow within a DIA-hour period, and a configurable minimum basal to use after that?  Would it be better to disable that by default if it's not configured, or to use some sort of default values (maybe 120m zero-temp, with a minimum of 50% of currently scheduled basal thereafter)?  Any other thoughts?

**Comment by scottleibrand** [comment]
Need a volunteer to drive this, or we need to decide we're not going to do it.  Any of y'all interested?

**Comment by bewest** [comment]
Ketones:

![image](https://cloud.githubusercontent.com/assets/394179/15442749/dcd90b46-1e97-11e6-9dc5-0c20711ec1fd.png)


Woke with heavy (70+) ketones. After this, I definitely think after some percentage of DIA has been covered, something different happens.  I usually hate on alarms, but I would be agreeable to working out some kind of alarm for this.  Maybe some notice for "ketones may be produced."

**Comment by amazaheri** [comment]
In our case since I get notifications from both openaps and nightscout via push for us if he is <= 70 we do carb correction. So alarm would work as long as it wakes u up or one of us call u.

**Comment by amazaheri** [comment]
btw any api access to nightscout for various alerts? it would be good to add if not already there so u can plug in ur method of choice pushover, azure push or ...

**Comment by bewest** [comment]
It could be that putting the feedback in BWP would have been enough.  The ketone thing was always lingering at the back of my mind, but I didn't realize quite what had happened until after.  (It's not displayed, bg meter 147 at 7:40pm, had four gummy bears at 6:30-ish).  The recalibration is shown ~9.

**Comment by CrushingT1D** [comment]
Yes. I want a configurable max time it can zero temp.

**Comment by sulkaharo** [comment]
Realized that it might be more useful to redefine this as "minimum required insulin flow / time period" rather than "prevent too much zero temping". AFAIK this is easier to calculate and would serve the same purpose, right?

**Comment by scottleibrand** [comment]
Gonna need one of you to volunteer to code and test this, as we never see this situation.

**Comment by Spazholio** [comment]
I'll throw my support behind this idea, as today something went very odd with my body, and I low-temped (with a small exception) for longer than my DIA.  I'm not nearly up to snuff on the code to write it though.

**Comment by scottleibrand** [comment]
What was the outcome of the long low-temp? Was this overnight or daytime? What did BG and IOB look like during the low-temp period?

**Comment by Spazholio** [comment]
Well, just a few hours later, I'm now up over 200 with a bullet, so...unsure.  It was daytime, from noon on to about 6:45pm.  Here's a pic from NS:

![image](https://cloud.githubusercontent.com/assets/18452263/16436947/6933bffe-3d70-11e6-90bc-f3d983466b1d.png)

**Comment by bewest** [comment]
That looks like compression low with the slow carbs catching up.  OY, unpleasant.

**Comment by Spazholio** [comment]
I don't think it's a compression low unless I'm misunderstanding what that means.  My sensor's on my stomach, and I haven't been lying down at all today or doing anything that could cause compression in that area.  But yeah, it's unpleasant - I'm definitely feeling the other side of the problem right now.  =)

**Comment by scottleibrand** [comment]
Looks like the 5pm calibration may have been off. Did you do any carb corrections for the lows before the 7pm meal? Did you bolus at all for that? Wondering why it didn't high temp for the rise after the carbs...

**Comment by Spazholio** [comment]
Right around 4:00 (I think), I ate a glucose tab.  I didn't notice the lows until that point.  At 6-ish, I ate 2 glucose tabs as well.  And 7pm wasn't a meal, I broke down and ate a Snickers because I was sick of the levels just not going up. And I just recalled - prior to that, I ate some meat and cheese.  Not to correct, but because I was a little hungry.  I suspect that's what delayed everything and caused it to shoot up a few hours later.  I've re-set my notifications to alert me sooner, so I should catch it before it gets to that point in the future.

**Comment by scottleibrand** [comment]
Seems like we're converging on a consensus that the right thing to do is to notify the user they may need to eat something, and then give insulin in response to that, rather than to give insulin, force a low, and force them to eat.  If so, is that something that belongs in oref0, or elsewhere?
