### ISSUE TITLE
Alerting framework?

### ISSUE THREAD

**Issue by scottleibrand** [openaps/oref0#57]
Can we build in some sort of alerting framework into oref0 that makes it easy to configure alerts for things we should be taking manual action on?

**Comment by jasoncalabrese** [comment]
If there was a new alerts.json file that we produce with a new tool, we could include it with the status upload to NS or use it in an other tool

**Comment by oskarpearson** [comment]
I was talking to Siobhan about this after a night with needless beeps and alarms from the pump :)

The pump was buzzing because her sugars were over the threshold - but they were definitely on their way down. We didn't need to be bothered.

We're still figuring out the right alert methods (eg: phone me, send bluetooth message, activate a buzzer in our self built box etc), but some sort of data output from oref0 would be great.

**Comment by audiefile** [comment]
I think that would be super helpful. Alerts could be much more customized - pushover alert for no loop for x minutes, text message for manual correction bolus, nightscout, etc. Could help with alarm fatigue - you only get notified when there is a problem not being addressed.

**Comment by amazaheri** [comment]
This sounds like a great idea, as we can use method of choice for alerting, Push over, Azure, etc. without having hard dependency on a specific method of delivery.
