### ISSUE TITLE
Extended 0 temp

### ISSUE THREAD

**Issue by sjolundjohn** [openaps/oref0#781]
I am having issues with the longer duration of 0.00 temps that are present in the Dev build. The problem I encounter is when I get a 2h extended 0.00 unit temp, then go out of range of my rig.

If I was in range, it would have corrected for it - but if I am out of range for a while, then I ended up going too high.

I would rather have 30min cycles OR the option to choose the max length.

**Comment by scottleibrand** [comment]
Are you using SMB?  If so, I would recommend going back to AMA on non-portable rigs that you tend to walk away from.  The SMB zero temps are a safety feature, and folks who find that safety feature problematic are typically using SMB in a less-safe way.

**Comment by sjolundjohn** [comment]
Yes I am on dev branch. It has been working super well and the SMB is a key reason for using it, but I do wish that it was less aggressive for the zero temp duration. I would think for portable rigs that refreshing every 30 minutes would have the same effect?

Feedback noted and I will consider. Thanks!

**Comment by JoseeT1Bionique** [comment]
I have experienced this also on Oref0 a few times and feel it is also an issue.
I agree that temp basal should be set for 30 minutes maximum and the be recalculated or defaulted to pump basal, at all time and with all settings. I would make me feel safer to have this in Dev 6 that I will start testing Thursday night.  We can predict or sometimes monitor/trouble shoot connection loss and 2 hours 0 basal is way to long.

**Comment by PieterGit** [comment]
@sjolundjohn @JoseeT1Bionique : 
With 0.6.x you can decrease the SMB's (and therefore the length of 0-temps) by decreasing `"maxSMBBasalMinutes"` to say 20 minutes. That way SMB's will be at most for 20 minutes of basal. The 0-temps will be shorter in that case as well. I used that when the CR/ISF values were not tuned (because I  went from multiple CR/ISF schedule to a single one).

**Comment by PieterGit** [comment]
Decreasing `maxSMBBasalMinutes` will probably not work (a lot) to shorten the 0-temps a lot, if no pump-rig communication is possible. I would like to 👎  implementing a way of shortening the 0-temps. Having a safe algorithm is more important than avoiding a high bg in case the pump-rig communication fails.

If you have thoughts that oref0 has an extended 0-temp that takes too long (and the rig can communicate to the pump), please open an issue for that.

**Comment by JoseeT1Bionique** [comment]
> Having a safe algorithm is more important than avoiding a high bg in case the pump-rig communication fails.

I agree.

**Comment by JELCRAWFORD** [comment]
If you are out of communication and realize you have a temp basal if zero that is not working you could always cancel the temp, which will revert the pump back to its program - presumably the user in this case (or their parent if they’ve been asked to cancel the temp) has used good reasoning in changing the temp based on current info. Once you are in range of the rig it will take over again for you. This seems the safest and simplest to me and avoids making changes to the safety measures intended in the algorithm.

**Comment by JoseeT1Bionique** [comment]
@JELCRAWFORD I agree it is a simple way and I've done it. But this assumes it is being caught. In the spirit that the APS, is to take our mind away from constant monitoring, if 30 is too short and could lead to too much insulin when reverting to pump setting, maybe the safety should be for 60 minutes instead of 120. I do not believe I've had a 120 minutes 0 temp ever go to the end with uninterrupted communication, they all revert before that time period is over.

**Comment by danamlewis** [comment]
Resolved via #844, so closing.
