### ISSUE TITLE
Suggestion: Safety setting in preferences.json "max_iob_during_exercise"

### ISSUE THREAD

**Issue by andrew-warrington** [openaps/oref0#795]
I would like to suggest a new safety setting, for during exercise: "max_iob_during_exercise". 

Background: Personal experience; I know if my IOB is above 1 while exercising then I cannot prevent a glucose drop without eating a huge amount of carb beforehand (i.e. a large meal with dessert). So I want to prevent OpenAPS from pushing my IOB above 1 while a high temp target is switched on.

Example: This morning I set a temp target of 140 while waiting to exercise, and ate 40g carb (fruit yogurt + coffee with cream and sugar) which I reported to Nightscout. As my glucose rose above the temp target, OpenAPS started high-temping, as expected. By the time I started exercising my glucose was 220 and IOB was 1.5. As expected based on the IOB, about 20 minutes into the exercise my glucose was shooting down past 100 and I had to stop to carb up again. I am using latest dev with exercise_mode on and half_basal_exercise_target as well.

I am aware that OpenAPS can't help if IOB is already above the temp safety zone, but at least it would zero temp in that case.

So, can we set a different max_iob during exercise?

**Comment by scottleibrand** [comment]
What are you changing half_basal_exercise_target to? Sounds like your sensitivityRatio was still too high for that kind of exercise. One way to tell if it’s low enough is to do the temp target first, and then see if it recommends as many carbs as you think you need. If not, the target may need to be higher or half_basal_exercise_target lower.

**Comment by andrew-warrington** [comment]
Thanks for the suggestions to help out with the example I gave.
What do you think of the safety setting suggestion? If there is a "max_iob" then shouldn't it be different during exercise? Could be an optional setting.

**Comment by scottleibrand** [comment]
I prefer not to add Yet Another Preference for something unless we can’t accomplish what we want to without it. If we were to change the max_iob behavior, it should be in a manner that is responsive to the actual value of the temp target: we use high temp targets with meals if we expect to walk home from the restaurant afterward, and wouldn’t want to overly constrain max_iob for a 111 temp target the same way as for a 140+ target. Right now, the auto-adjustments to sensitivityRatio accomplish the IOB limitation well IMO, but if we decide that is insufficient we could for example divide max_iob by sensitivityRatio, so that when temp target is at half_basal_exercise_target the max_iob is half of what it normally is. Or maybe we would need to divide by the square of sensitivityRatio or something...

**Comment by tepidjuice** [comment]
I agree with Scott. In my opinion max_iob is a pretty blunt safety cap.

I think this should be covered by the ISF change in exercise mode. Theoretically you could need a lot of insulin during exercise if you ate enough. So I wouldn't want to stop the rig from being able to cover that.

Maybe the ISF change in exercise mode should cover CSF as well?

**Comment by scottleibrand** [comment]
Sounds like we've addressed this?  Please reopen if you want to continue the discussion, or feel free to open a new issue or PR with anything else.
