### ISSUE TITLE
Timezone doesn't handle daylight savings time well

### ISSUE THREAD

**Issue by audiefile** [openaps/oref0#85]
All times and time zones were set correctly but pump history wasn't properly zoned so treatments were displayed in Nightscout as off by one hour (one hour into the future).

**Comment by scottleibrand** [comment]
Looks like this is because initial device setup sets something like PST in the openaps.ini, which doesn't get updated automatically for DST, so you have to manually change it to PDT.  Need to make tz smarter about switching back and forth when appropriate, or using the system timezone at runtime instead of configure time.

**Comment by audiefile** [comment]
+1

**Comment by scottleibrand** [comment]
Just noticed this issue is in oref0.  It really should be in openaps/openaps instead.  We already have https://github.com/openaps/oref0/issues/83 open for oref0.

**Comment by audiefile** [comment]
Oops! Just opened #86 in openaps so I'll close this one.
