### ISSUE TITLE
第一次使用open，结果edison连不到泵上，怎么办？

### ISSUE THREAD

**Issue by jzycom123** [openaps/oref0#890]
第一次使用open，结果edison连不到泵上，怎么办？

**Comment by scottleibrand** [comment]
https://translate.google.com/#auto/en/%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8open%EF%BC%8C%E7%BB%93%E6%9E%9Cedison%E8%BF%9E%E4%B8%8D%E5%88%B0%E6%B3%B5%E4%B8%8A%EF%BC%8C%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F translates that to: "The first time the use of open, edison failed to pump the results, what should I do?"

The best place to start for troubleshooting is http://openaps.readthedocs.io/en/latest/docs/Troubleshooting/

If that doesn't address your issue, http://openaps.readthedocs.io/en/latest/docs/Understanding%20OpenAPS-Overview/communication-support-channels.html is a page with some details on where to get help.  Generally we find that Gitter (https://gitter.im/nightscout/intend-to-bolus) is the best place to start.  There are even a few people on there such as @denglfddd who speak Chinese.

In addition, https://diyps.org/2017/03/19/tips-for-troubleshooting-diy-diabetes-devices-openaps-or-otherwise/ has some good tips for what kind of information we'll need to help you.

Translated to Chinese / 翻译成中文:

开始排除故障的最佳位置是http://openaps.readthedocs.io/en/latest/docs/Troubleshooting/

如果这不能解决您的问题，http://openaps.readthedocs.io/en/latest/docs/Understanding%20OpenAPS-Overview/communication-support-channels.html是一个页面，提供有关获取帮助的一些详细信息。 一般来说，我们发现Gitter（https://gitter.im/nightscout/intend-to-bolus）是最好的开始。 那里还有几个人，比如@denglfddd谁会讲中文。

此外，https://diyps.org/2017/03/19/tips-for-troubleshooting-diy-diabetes-devices-openaps-or-otherwise/有一些很好的提示，我们需要什么样的信息来帮助 您。

**Comment by StephenJoker** [comment]
> 第一次使用open，结果edison连不到泵上，怎么办？

您好，我是一名工业设计师，也是一位糖尿病患者的儿子，我最近也在关注OpenAPS 项目，您是我在网上查到的唯一一位在关注此项目的中国人，因此非常希望与您取得联络，您可查看我的主页找到我的邮箱和微信联系方式。
