### ISSUE TITLE
Loop doesn't start on 712 pump

### ISSUE THREAD

**Issue by Plukius** [openaps/oref0#956]
This is my first experience with openAPS, I am trying to get a loop working, but get stuck on repetitive error messages. I have an Edison with explorer board, flashed it from a Mac, followed all the steps of 'Installing OpenAPS on your rig'. I have a 712 pump with new battery, pump is next to the rig. I have run the setup script for more than an hour, and the loop doesn't get started. I get the following messages, on which I think it is stuck:

Old pumphistory: IndexError: bytearray index out of range
grep: monitor/temp_basal.json: No such file or directory

Any idea on what is going on and how I can fix this?
Maybe related: I noticed that when building the setup script, I get a lot of warnings like these, which seem to indicate that my rig somehow has a too old version of node :
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})

Thanks!

**Comment by Plukius** [comment]
All right, I couldn't fix it. Luckily I got access to another pump (a 722), ran the setup script, and the loop started without any problems so far! So most likely something was broken in the 712 I had.

**Comment by AndreasSpeer** [comment]
Hi
Has anyone already solved this problem?
I also have a 712 and despite additional installation of
nano ~ / myopenaps / settings / basal_profile.json
nano ~ / myopenaps / settings / settings.json and
nano ~ / myopenaps / settings / settings.json

the error messages
Old pumphistory: IndexError: bytearray index out of range
grep: monitor / temp_basal.json: No such file or directory

Thank you!

**Comment by danamlewis** [comment]
@AndreasSpeer that error means it hasn't got a good pump read. That could be a transient error that self resolves (usually the case with an otherwise working setup), or it could point to something else about it not being able to read the pump. Things to check: look at mmtune logs and see what the signal strength is for reading the pump. Double check that the pump SN is correct, etc. Hop onto Gitter if you'd like to real-time troubleshoot on any of these.
