### ISSUE TITLE
Suggestion/idea: allow setting temp targets from the pump when offline

### ISSUE THREAD

**Issue by alimhassam** [openaps/oref0#972]
I had an idea today, and was wondering if it was a reasonable idea that others thought might be useful. 

I was offline today with no internet connectivity while taking my kids swimming, and wanted to set a temp target to avoid going low and thought it would be nice to be able to do that by just changing the target in the pump.

The target range in the pump is pretty static curently, we don't change it very much, not sure if others do and for what use cases.  

Correct me if i'm wrong, but i think that currently changing the target in the pump is not the same as setting a temp target.

My idea, which I think might be useful is to move the actual default target setting to the preference file instead and treat the pump target as a temp target when it differs.

Would that be a useful feature? Seems to me like this would be a nice and easy way to set temp targets when offline. What do other think?

**Comment by scottleibrand** [comment]
So if you, for example, set a target > 90 in the preference file and set <= 90 on the pump, and have low_temptarget_lowers_sensitivity enabled, that would force the sensitivityRatio up to ~1.2x, regardless of how sensitive you're actually running.  Since there's no expiration time on pump targets, that means it would by default stay that way indefinitely: I'm not sure that's ideal from a safety perspective.

FWIW, the Explorer HAT menu and buttons do allow for setting temp targets while offline.  Perhaps we should focus on making that user interface more user-friendly?

**Comment by danamlewis** [comment]
We've tested something on my rigs where it sets a temp target by default when I go offline, and that's working well. Most users are currently using the HAT menu to do this, though.  @alimhassam closing this due to lack of discussion in past 1.5 year, but please reopen and comment if you're interested in our local change (setting a temp target by default when offline) being added into the next release (after 0.7.0) for your use case as well.
