### ISSUE TITLE
Proposal for discussion: microBolus minimum interval strategy

### ISSUE THREAD

**Issue by AdrianLxM** [openaps/oref0#988]
I would propose replacing the following code that guards from too frequent microboluses...
```
if (lastBolusAge > 3) {
    if (microBolus > 0) {
        rT.units = microBolus;
        rT.reason += "Microbolusing " + microBolus + "U. ";
    }
} else {
    rT.reason += "Waiting " + nextBolusMins + "m " + nextBolusSeconds + "s to microbolus again. ";
}
```
with just
```
    if (microBolus > 0) {
        rT.units = microBolus;
        rT.reason += "Microbolusing " + microBolus + "U. ";
    }
```
and add 
```
else if (lastBolusAge < 3) {
        console.error("SMB disabled due to short interval. Waiting " + nextBolusMins + "m " + nextBolusSeconds + "s);
        enableSMB=false;
}
```
here: https://github.com/openaps/oref0/blob/3881f938ebf2a54b517b41a6b825bb2faa4f2299/lib/determine-basal/determine-basal.js#L369 (where SMB gets disabled due to a high target etc.)

The advantage I see is that it will not set a low-temp already calculating in the SMB but do the calculation knowing beforehand that it cannot microbolus.

**Comment by scottleibrand** [comment]
That doesn’t sound like the behavior we want. When you’re SMBing, and a second rig determines it's too soon to SMB again, we want it to leave the zero temp running, and SMB at the next opportunity. We don’t want the second rig to be constantly replacing the first rig’s zero temp with a nonzero temp just because it’s not time to SMB yet.

**Comment by scottleibrand** [comment]
The relatively common OpenAPS two-rig scenario is one example, but the same thing is true if AndroidAPS runs determine-basal more often than once every 3 minutes.  One thing to keep in mind is that, while the "about to SMB" condition is necessary to allow an SMB zero-temp, it's not always sufficient.  For example, if you enter carbs but haven't bolused yet, SMB will set a maxBasal high temp, then try to SMB, and then immediately reduce the basal on the next run (whether or not it's time to SMB again yet) once it sees the SMB has gone through, until it gets enough IOB to warrant constant zero-temping as it SMBs.  That is the desired behavior, not an undesirable side effect.

We do not recommend running multiple rigs with different configs.  If people want daytime SMBs but not nighttime, there are a number of enableSMB preference options to support that.

When two rigs with the same settings run in parallel, they do a couple random-duration `sleep`s and `wait_for_silence`s to try to make sure that only one rig is running at a time.  But more importantly, they also check the reservoir level before checking pumphistory, and check bolusing status and reservoir level again right before bolusing, so you can't have two rigs both deliver SMBs of more than about 0.1U.  And since the bolus amount is limited to insulinReq/2, you can never have simultaneous small boluses deliver more than the insulinReq even in the race condition.
